### ISSUE TITLE
Make MME FQDN name configurable

### ISSUE THREAD

**Issue by krsna1729** [omec-project/c3po#1]
Currently its hardcoded to `mme.localdomain`

- [x] https://github.com/omec-project/c3po/blob/master/hss/src/fdhss.cpp#L155-L156
- [x] https://github.com/omec-project/c3po/blob/master/db_docs/data_provisioning_users.sh#L37

**Comment by lbertz02** [comment]
Note that fdhss.cpp references a TODO with an MME db.   What is the plan for replacing the 'db'?  Will it be a list in the config file or an option to point to a db?

**Comment by krsna1729** [comment]
Linked the PR now. The TODO continues. Need to open a tracker for all such TODOs in the code. For now a hotfix is up in a PR. This is blocker to operate in a dynamic environment. Use case - kubernetes

**Comment by krsna1729** [comment]
For now atleast we consume an environment variable

**Comment by krsna1729** [comment]
if there is development to supersede the PR, i am happy.

**Comment by lbertz02** [comment]
there isn't any that I am aware of atm
