### ISSUE TITLE
Version update: Attestation service for Intel SGX API should be updated to use V3

### ISSUE THREAD

**Issue by suresh-marikkannu** [omec-project/c3po#18]
Currently used  version of Attestation Service for Intel(R) Software Guard Extensions API has reached end of life and is no longer available. Need to update the version.

Current: https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v2/report
To be Updated: https://test-as.sgx.trustedservices.intel.com:443/attestation/sgx/v3/report

Following files to be updated:
    sgxcdr/dealer/App/ias-ra.c
    sgxcdr/kms/App/ias-ra.c

**Comment by micpez** [comment]
This can be closed. See https://github.com/omec-project/c3po/pull/19
