### ISSUE TITLE
Git repository not found

### ISSUE THREAD

**Issue by omeshF** [omec-project/c3po#24]
Hi, I have Ubuntu16.04 and I'm trying to install c3po. 
I'm following instructions in the https://github.com/omec-project/c3po. 
I can't clone into the repository. 
After the command git clone https://gerrit.opencord.org/c3po
I get and error message as 

Cloning into 'c3po'...
fatal: remote error: Git repository not found

Please provide feedback.
Thank you

**Comment by Sandeep-Sarma** [comment]
Hi, you can clone using the same path as you're in now. ie: https://github.com/omec-project/c3po.git

BR,
Sandeep

**Comment by krsna1729** [comment]
@omec-project/docs c3po docs need to reflect new URLs

**Comment by krsna1729** [comment]
@omeshF thanks for opening the issue!

**Comment by omeshF** [comment]
@Sandeep-Sarma  Thank you for your help.
