### ISSUE TITLE
cd {installation_root}/mme not available 

### ISSUE THREAD

**Issue by omeshF** [omec-project/c3po#25]
Hello. 

On the **Provisioning** Section 1 (d) cd {installation_root}/mme 
There's no mme folder. 
Hence the command 
./bin/hss -j conf/hss.json --onlyloadkey

can not be executed. 
Please provide feedback
Thank you

Best wishes
Omesh

**Comment by Sandeep-Sarma** [comment]
Hi,
Looks like a typo. Should have been cd {installation_root}/hss

BR,
Sandeep
