### ISSUE TITLE
Docker image creation failed.

### ISSUE THREAD

**Issue by wanare-2017** [omec-project/c3po#35]
While trying to create docker image for c3po project, but docker image creation was failed and  getting below error. 

W: http://ubuntu-archive.mirrors.estointernet.in/ubuntu/pool/main/g/gdbm/libgdbm3_1.8.3-13.1_amd64.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)
Installing freeDiameter
CMake Error: The source directory "/c3po/modules/freeDiameter" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
The command '/bin/sh -c ./install_builddeps.sh' returned a non-zero code: 1

**Comment by hyunsun** [comment]
Hi, try `git submodule init && git submodule update` under c3po repo and then make docker-build again.
