### ISSUE TITLE
Adding user via data_provisioning_users.sh fails

### ISSUE THREAD

**Issue by bedrankara** [omec-project/c3po#50]
Hello,

I am currently trying to set up the project. While trying to add a user to the db via the **data_provisioning_users.sh** I get the following error. 

` Error: Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level ONE" info={'required_replicas': 1, 'alive_replicas': 0, 'consistency': 'ONE'}`

I use the following command :

`./bin/data_provisioning_users.sh 001010000000203 017612345678  internet 00112233445566778899aabbccddeeff 1 172.28.0.2 63bfa50ee6523365ff14c1f45f88737d mme.openair4G.eur openair4G.eur
`

The only succesfull entry I can make is when setting the number_of_users parameter to 0.

**Comment by thakurajayL** [comment]
Log message says that you need replica. Can you share how you deployed your database.
